[project]
name = "repomgr"
version = "0.1.0"
description = "Automatically manage git repositories"
readme = "readme.md"
requires-python = ">=3.12"
dependencies = [
    "pygit2>=1.16.0",
    "rich>=13.9.2",
    "ruff>=0.7.0",
    "tomlkit>=0.13.2",
]
